version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: script/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/SetFilePermission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root 
